# @package _global_
defaults:
    - override /datasets: d4rl

tokenizers:
    states:
      _target_: research.omtm.tokenizers.continuous.ContinuousTokenizer.create
    actions:
      _target_: research.omtm.tokenizers.continuous.ContinuousTokenizer.create
    returns:
      _target_: research.omtm.tokenizers.continuous.ContinuousTokenizer.create
    rewards:
      _target_: research.omtm.tokenizers.continuous.ContinuousTokenizer.create



dataset:
    use_reward: True
    env_name: "hopper-medium-replay-v2"
    train_val_split: 0.95

wandb:
    project: "pretrain"
    resume: null
